# module.exports = {
#   extends: [
#     // add more generic rulesets here, such as:
#     'eslint:recommended',
#     'plugin:vue/vue3-recommended',
#     // 'plugin:vue/recommended' // Use this if you are using Vue.js 2.x.
#   ],
#   rules: {
#     // override/add rules settings here, such as:
#     // 'vue/no-unused-vars': 'error'
#   }
# }
env:
  es2020: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'prettier'
  # - 'plugin:@typescript-eslint/recommended'
  # - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  # - 'prettier'
  # - 'prettier/@typescript-eslint'
